name: last_save
description: A contextual contact management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.0+1
  flutter_contacts: ^1.1.9+2
  shared_preferences: ^2.5.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.1
  sign_in_with_apple: ^7.0.1
  cloud_firestore: ^4.9.1
  connectivity_plus: ^4.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png










