// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC69odGbD2xnonGryV2A0eTk7fUHS7zSeU',
//     appId: '1:75133745727:web:c08a6baab9721be12bd68a',
//     messagingSenderId: '75133745727',
//     projectId: 'last-save',
//     authDomain: 'last-save.firebaseapp.com',
//     storageBucket: 'last-save.firebasestorage.app',
//     measurementId: 'G-HJWECSGGSV',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDHtnywQqNpUk-fi7jNUfvIk5Nz4GLgOnY',
//     appId: '1:75133745727:android:3adaadb7b425379c2bd68a',
//     messagingSenderId: '75133745727',
//     projectId: 'last-save',
//     storageBucket: 'last-save.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDbPtRRB7Pix3ugoJlHevhl3DaZrGFh7BA',
//     appId: '1:75133745727:ios:b0cf6e410dd8b6d52bd68a',
//     messagingSenderId: '75133745727',
//     projectId: 'last-save',
//     storageBucket: 'last-save.firebasestorage.app',
//     iosClientId: '75133745727-ej1gde8clcusdlicp584o6a7h8to2ttk.apps.googleusercontent.com',
//     iosBundleId: 'com.example.lastSave',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDbPtRRB7Pix3ugoJlHevhl3DaZrGFh7BA',
//     appId: '1:75133745727:ios:b0cf6e410dd8b6d52bd68a',
//     messagingSenderId: '75133745727',
//     projectId: 'last-save',
//     storageBucket: 'last-save.firebasestorage.app',
//     iosClientId: '75133745727-ej1gde8clcusdlicp584o6a7h8to2ttk.apps.googleusercontent.com',
//     iosBundleId: 'com.example.lastSave',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC69odGbD2xnonGryV2A0eTk7fUHS7zSeU',
//     appId: '1:75133745727:web:55bb874fcf96e7cd2bd68a',
//     messagingSenderId: '75133745727',
//     projectId: 'last-save',
//     authDomain: 'last-save.firebaseapp.com',
//     storageBucket: 'last-save.firebasestorage.app',
//     measurementId: 'G-DJBSQXSM7G',
//   );
// }
